package main
import "packagecreation/Basic"
func main(){
	Basic.ScanInput()
	// Basic.Ascii()
	// Basic.Conversion()
	// Basic.ComplexDatattype()
	// Basic.ConstantDatatype()
	// Basic.Iota()
	// Basic.IotaSkipValues()
	// Basic.ArrrayDeclaration()
	// Basic.DynamicArray()
	// Basic.ArrayLength()
	// Basic.ReplaceValueAtIndex()
	// Basic.Copy_OneArray_TO_Another()
	// Basic.PrintSubarray()
	// Basic.MultidimensionalArray()
	// Basic.Map()
	//  Basic.Put_Delete_in_map()
	//  Basic.ContainsKey_thenPrint()
	//Basic.Copy_Map_Trap()
	// Basic.Slicing()
	// Basic.SlicingTrap()
	// Basic.Slicing_append()
//	Basic.Struct()
// Basic.Forloop()
Basic.Continue()
// Basic.ForRange()
//Basic.IfElse()
//Basic.IfElseIf()
	//Basic.Switch()
	// Basic.FallThrough()
	//Basic.Break()
}
