package main
import "packagecreation/Basic"
func main(){
	//  Basic.ScanInput()
	// Basic.ArrayInput()
	// Basic.Ascii()
	//  Basic.Conversion()
// Basic.TypeConversion()
     //Basic.Reflect()
	// Basic.ComplexDatattype()
	// Basic.ConstantDatatype()
	// Basic.Iota()
	// Basic.IotaSkipValues()
	//Basic.StringIndex()
	//Basic.Rune()
	// Basic.Runeexp()
	// Basic.ArrrayDeclaration()
	// Basic.DynamicArray()
	// Basic.ArrayLength()
	// Basic.MultiDemArray()
	// Basic.ReplaceValueAtIndex()
	// Basic.Copy_OneArray_TO_Another()
	// Basic.PrintSubarray()
	// Basic.MultidimensionalArray()
	// Basic.Map()
	// Basic.Put_Delete_in_map()
	// Basic.ContainsKey_thenPrint()
	// Basic.Copy_Map_Trap()
	// Basic.Slicing()
	// Basic.SlicingTrap()
	// Basic.Slicing_append()
	// Basic.Struct()
	//Basic.StructInheritance()
	//Basic.StructTags()
	// Basic.Forloop()
	// Basic.Goto()
	// Basic.Continue()
	// Basic.ForRange()
	// Basic.IfElse()
	// Basic.IfElseIf()
	// Basic.Switch()
	// Basic.FallThrough()
	// Basic.Break()
	// Basic.Defer()
//  Basic.Defercase()
	// Basic.Pointer()
	// Basic.StructPointer()
	// Basic.PointerExp()
	// Basic.PointerExp2()
	//Basic.PointertoPointer()
	// Basic.BasicFunc()
	// Basic.ReturnDataTypeFunc()
	// Basic.VariadicFunc()
	// Basic.MultipleReturnFunc()
	// Basic.StructTypeFunc()
	//Basic.Structargpass()
	// Basic.Anonymounsfunc()
	// Basic.Interface()
	// Basic.Interface2()
	// Basic.CallByReference()
	//Basic.CallByValue()
	// Basic.Recursion()
	// Basic.Bitwise()
	// Basic.BitShifting()
	// Basic.Goroutine1()
	// Basic.Goroutine2()
	// Basic.Goroutine3()
	// Basic.Goroutine4()
	// Basic.Channel()
	//Basic.Channel1()
	// Basic.Channel2()
	// Basic.Channel3()
	// Basic.Channel4()
	Basic.Channel6()
	// Basic.BufferedChannel()
	// Basic.Panic()
	//Basic.Panic2()
	// Basic.Recover()
}
